name: timepal
description: "TimePal - 智能习惯追踪与游戏化应用"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # 状态管理
  provider: ^6.0.5

  # HTTP客户端
  dio: ^5.3.2

  # 本地存储
  shared_preferences: ^2.2.2

  # SQLite数据库
  sqflite: ^2.3.0

  # WebView组件
  webview_flutter: ^4.4.2

  # 本地通知
  flutter_local_notifications: ^16.3.0

  # 图片选择
  image_picker: ^1.0.4

  # 图表组件
  charts_flutter: ^0.12.0

  # 网络图片缓存
  cached_network_image: ^3.3.0

  # 图标
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
